name: CI

on:
  push:
    branches:
      - main
      - renovate-github/**
  pull_request:

jobs:
  node-version:
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.nvmrc.outputs.node-version }}
    steps:
      - uses: actions/checkout@v7
      # Read node version from `.nvmrc` file
      - id: nvmrc
        run: |
          echo "node-version=$(cat .nvmrc)"
          echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

  main:
    needs: node-version
    name: Nx CI
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ needs.node-version.outputs.node-version }}
      - uses: nrwl/nx-set-shas@v4
      - name: Install dependencies
        run: npm ci
      - name: Format check
        run: npx nx format:check
      - name: Build affected
        run: npx nx affected --target=build
      - name: Lint affected
        run: npx nx affected --target=lint
      - name: Test
        run: npx nx ${{ github.event_name == 'pull_request' && 'affected' || 'run-many --all' }} --target=test --ci
      - name: E2E
        run: npx nx ${{ github.event_name == 'pull_request' && 'affected' || 'run-many --all' }} --target=e2e --parallel=1 --ci
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: nx-main-artifacts
          path: ./coverage

  codecov:
    name: Coverage Report
    needs: main
    if: success() && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: 'Downloading artifacts'
        uses: actions/download-artifact@v8
        with:
          name: nx-main-artifacts
          path: ./coverage
      - name: 'Codecov'
        uses: 'codecov/codecov-action@v7.0.0'
        if: hashFiles('coverage/**/*') != ''
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
