name: CI

on:
  push:
    branches:
      - main
      - renovate-github/**
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11
    with:
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3
      artifacts-path: ./coverage

  codecov:
    name: Coverage Report
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: 'Downloading artifacts'
        uses: actions/download-artifact@v3
        with:
          name: nx-main-artifacts
          path: ./coverage
      - name: 'Codecov'
        uses: 'codecov/codecov-action@v3.1.1'
        if: hashFiles('coverage/**/*') != ''
        with:
          fail_ci_if_error: true
          verbose: true

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    with:
      number-of-agents: 3
